apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster-worker
  namespace: taskmaster-dev
  labels:
    app: taskmaster-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmaster-worker
  template:
    metadata:
      labels:
        app: taskmaster-worker
    spec:
      containers:
      - name: worker
        image: mathade/taskmaster-worker:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
