apiVersion: v1
kind: Service
metadata:
  name: taskmaster-api
  namespace: taskmaster-dev
spec:
  selector:
    app: taskmaster-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
