apiVersion: v1
kind: Service
metadata:
  name: taskmaster-frontend
  namespace: taskmaster-dev
spec:
  selector:
    app: taskmaster-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
